const ICONS = {
  EXPORT: "/assets/icons/export.svg",
  ADD_CIRCLE: "/assets/icons/add-circle.svg",
  ADD: "/assets/icons/user.svg",
  ADD_ACTIVE: "/assets/icons/user-active.svg",
  IMPORT: "/assets/icons/file-add-black.svg",
  IMPORT_ACTIVE: "/assets/icons/file-add-active.svg",
  VIEW: "/assets/icons/view.svg",
  EDIT: "/assets/icons/edit.svg",
  DELETE: "/assets/icons/trash.svg",
  DOWNLOAD_TEMPLATE: "/assets/icons/download-template.svg",
  USER: "/assets/icons/user.svg",
  USER_ACTIVE: "/assets/icons/user-active.svg",
  PEN: "/assets/icons/pen.svg",
  PEN_ACTIVE: "/assets/icons/pen-active.svg",
  PROFESSIONAL: "/assets/icons/professional.svg",
  PROFESSIONAL_ACTIVE: "/assets/icons/professional-active.svg",
  GMAIL: "/assets/icons/gmail.svg",
  PEN_UNDERLINE: "/assets/icons/edit-profile.svg",
  CHANGE_PHOTO: "/assets/icons/image-edit.svg",
  TICK: "/assets/icons/tick.svg",
  REMOVE: "/assets/icons/remove.svg",
  FILE_DOC: "/assets/icons/file-doc.svg",
  DATE: "/assets/icons/calendar.svg",
  USER_ADMIN: "/assets/icons/user-admin.svg",
  // sidebar
  DASHBOARD: "/assets/icons/dashboard.svg",
  DASHBOARD_ACTIVE: "/assets/icons/dashboard-active.svg",
  COMPANY_PROFILE: "/assets/icons/company-profile.svg",
  COMPANY_PROFILE_ACTIVE: "/assets/icons/company-profile-active.svg",
  ALL_DEPARTMENTS: "/assets/icons/all-departments.svg",
  ALL_DEPARTMENTS_ACTIVE: "/assets/icons/all-departments-active.svg",
  ALL_EMPLOYEES: "/assets/icons/all-employees.svg",
  ALL_EMPLOYEES_ACTIVE: "/assets/icons/all-employees-active.svg",
  ATTENDANCES: "/assets/icons/attendance.svg",
  ATTENDANCES_ACTIVE: "/assets/icons/attendance-active.svg",
  LEAVES: "/assets/icons/leaves.svg",
  LEAVES_ACTIVE: "/assets/icons/leaves-active.svg",
  HOLIDAYS: "/assets/icons/holidays.svg",
  HOLIDAYS_ACTIVE: "/assets/icons/holidays-active.svg",
  SETTINGS: "/assets/icons/settings.svg",
  SETTINGS_ACTIVE: "/assets/icons/settings-active.svg",
  // Sidebar employee details
  USER_PROFILE_ACTIVE: "/assets/icons/user-profile-active.svg",
  ATTENDANCES_PROFILE_ACTIVE: "/assets/icons/attendance-profile-active.svg",
  LEAVES_PROFILE_ACTIVE: "/assets/icons/leaves-profile-active.svg",
};

export default ICONS;
